include: "rules/download_data.skm"

rule all:
    input:
        expand("featureCounts/{sample}.gene_count.txt", sample=SAMPLES)
 
rule whippet:
    input:
        expand("Whippet/Quant/{sample}.psi.gz", sample=SAMPLES)
        

rule hisat2_Genome_index:
    input:
        "Genome/dm6.fa"
    output:
        "Genome/Index/dm6.1.ht2"
    threads: 5
    conda:
        "envs/core.yaml"
    log:
        "logs/hisat2_Genome_index.log"
    shell:
        "hisat2-build -p 5 {input} Genome/Index/dm6 2> {log}"

rule hisat2_to_Genome:
    input:
        fastq = "FASTQ/{sample}.fastq.gz",
        genome = "Genome/Index/dm6.1.ht2"
    output:
        "hisat2/{sample}.sam"
    threads: 5
    conda:
        "envs/core.yaml"
    log:
        "logs/hisat2_to_Genome.{sample}.log"
    shell:
        "hisat2 -p 5 -U {input.fastq} -x  Genome/Index/dm6  > {output} 2> {log}"

rule samTobam:
    input:
        temp("hisat2/{sample}.sam")
    output:
        "hisat2/{sample}.sorted.bam"
    conda:
        "envs/core.yaml"
    shell:
        "samtools view -b  {input}  | samtools sort - -o {output} && samtools index {output}"

rule featureCounts:
    input:
        gtf = "Gene_annotation/dm6.Ensembl.genes.gtf",
        bam = "hisat2/{sample}.sorted.bam"
    output:
        "featureCounts/{sample}.gene_count.txt"
    threads: 1
    conda:
        "envs/core.yaml"
    log:
        "logs/featureCounts.{sample}.log"
    shell:
        "featureCounts -a {input.gtf} -o {output} {input.bam} 2> {log}"
